# oh-my-zsh

[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.zip"
# exact = true
stripComponents = 1
refreshPeriod = "168h"

##############################################################################
## oh-my-zsh plugins
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
type = "git-repo"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/conda-zsh-completion"]
type = "git-repo"
url = "https://github.com/esc/conda-zsh-completion.git"
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/tldr-zsh-completion/tldr-zsh-completion.plugin.zsh"]
type = "file"
url = "https://raw.githubusercontent.com/tldr-pages/tldr-c-client/main/autocomplete/complete.zsh"
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-better-npm-completion"]
type = "git-repo"
url = "https://github.com/lukechilds/zsh-better-npm-completion"
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-vi-mode"]
type = "git-repo"
url = "https://github.com/jeffreytse/zsh-vi-mode"
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/alembic-completions"]
type = "git-repo"
url = "https://github.com/datumbrain/oh-my-zsh-alembic"
stripComponents = 1
refreshPeriod = "168h"

##############################################################################
## oh-my-zsh themes
[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git-repo"
url = "https://github.com/romkatv/powerlevel10k.git"
stripComponents = 1
refreshPeriod = "168h"
